name: lokalapp
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  after_layout: ^1.1.0
  carousel_slider: ^2.3.1
  cloud_firestore: ^0.16.0
  cloud_functions: ^0.9.0
  cupertino_icons: ^1.0.0
  dropdown_date_picker: ^0.1.1+2
  emoji_picker: ^0.1.0
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.0
  flutter_facebook_auth: ^1.0.0
  flutter_onboard: ^0.1.0
  flutter_screenutil: ^5.0.0+2
  flutter_simple_rating_bar: ^0.0.3
  flutter_sliding_up_panel: ^1.1.0+1
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.19.3
  geolocator: ^3.0.1
  google_fonts: ^1.1.1
  google_sign_in: ^4.5.9
  grouped_list: ^4.0.0
  http: ^0.12.2
  image: ^2.1.19
  image_picker: ^0.6.7+14
  intl: ^0.16.1
  jiffy: ^3.0.1
  location: ^3.1.0
  material_design_icons_flutter: ^4.0.5955
  modal_progress_hud: ^0.1.3
  path_provider: ^1.6.24
  # this is a modified persistent-bottom-nav-bar that uses NestedWillPopScope
  persistent_bottom_nav_bar:
    git: https://github.com/jaypatvin/persistent-bottom-nav-bar
  photo_manager: ^0.5.8
  photo_view: ^0.11.1
  photo_widget: ^0.0.3
  pk_skeleton: ^0.0.2
  provider: ^4.3.2+2
  rflutter_alert: ^2.0.2
  shared_preferences: ^0.5.12+4
  sliding_up_panel: ^1.0.2
  start_jwt: ^0.2.0
  swipe_to: ^0.0.1+8
  uuid: ^2.2.2
  validators: ^3.0.0
  velocity_x: ^1.0.1
  wechat_camera_picker: ^1.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bottomNavIcons/
    - assets/payment/
    - assets/sso/
  fonts:
    - family: Goldplay
      fonts:
        - asset: assets/fonts/Goldplay-Thin.otf
          weight: 200
        - asset: assets/fonts/Goldplay-Light.otf
          weight: 300
        - asset: assets/fonts/Goldplay-Regular.otf
          weight: 400
        - asset: assets/fonts/Goldplay-Medium.otf
          weight: 500
        - asset: assets/fonts/Goldplay-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Goldplay-Bold.otf
          weight: 700
        - asset: assets/fonts/Goldplay-Black.otf
          weight: 900
