name: lokalapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.49

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  after_layout: ^1.1.0
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.4
  collection: ^1.15.0-nullsafety.4
  connectivity_plus: ^2.1.0
  crypto: ^3.0.1
  cupertino_icons: ^1.0.3
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  firebase_crashlytics: ^2.5.0
  firebase_storage: ^10.0.5
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^4.0.1
  flutter_hooks: ^0.18.1
  flutter_image_compress: ^1.1.0
  flutter_rating_bar: ^4.0.0
  flutter_screenutil: ^5.1.0
  flutter_staggered_grid_view: ^0.6.0
  flutter_svg: ^1.0.0
  focused_menu: ^1.0.5
  google_sign_in: ^5.1.1
  grouped_list: ^4.1.0
  http: ^0.13.4
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  jiffy: ^5.0.0
  keyboard_actions: ^3.4.7
  localstorage: ^4.0.0+1
  lottie: ^1.2.1
  material_design_icons_flutter: ^5.0.6295
  oktoast: ^3.1.5
  path_provider: ^2.0.5
  permission_handler: ^9.2.0
  persistent_bottom_nav_bar: # this is a modified persistent-bottom-nav-bar that uses NestedWillPopScope
    git:
      url: https://github.com/jaypatvin/PersistentBottomNavBar
      ref: master
  photo_manager: ^1.3.7
  photo_view: ^0.13.0
  provider: ^6.0.1
  recase: ^4.0.0
  rflutter_alert: ^2.0.4
  shared_preferences: ^2.0.8
  shimmer_animation: ^2.1.0+1
  sign_in_with_apple: ^3.2.0
  swipe_to: ^0.1.0-nullsafety.1
  uuid: ^3.0.5
  validators: ^3.0.0
  visibility_detector: ^0.2.2
  webview_flutter: ^3.0.0
  wechat_camera_picker: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.1
  test: ^1.17.12

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/bottomNavIcons/
    - assets/payment/
    - assets/rating/
    - assets/sso/
  fonts:
    - family: Goldplay
      fonts:
        - asset: assets/fonts/Goldplay-Thin.otf
          weight: 200
        - asset: assets/fonts/Goldplay-Light.otf
          weight: 300
        - asset: assets/fonts/Goldplay-Regular.otf
          weight: 400
        - asset: assets/fonts/Goldplay-Medium.otf
          weight: 500
        - asset: assets/fonts/Goldplay-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Goldplay-Bold.otf
          weight: 700
        - asset: assets/fonts/Goldplay-Black.otf
          weight: 900
