default_platform(:ios)

platform :ios do

  desc "Increment Build Number"
  lane :increment_build do
    # increment build number
    increment_build_number
    version = get_version_number(xcodeproj: "Runner.xcodeproj")
    build_number = get_build_number(xcodeproj: "Runner.xcodeproj")
    version_string = "#{version}.#{build_number}"

    # Commit changes
    # puts "Updated iOS  version to #{version_string}"
    # echo "Updated iOS  version to #{version_string}"

    # sh "git commit -a -m \"Updated iOS version to #{version_string}\""
    # add_git_tag(tag: "#{version_string}")
    # push_to_git_remote
  end

  desc "Make iOS Build"
  lane :build do
    # Build iOS
    build_ios_app(
      clean: true,
      workspace: 'Runner.xcworkspace',
      scheme: 'Runner',
      export_method: 'ad-hoc',
      output_directory: "build/"
    )
  end

  desc "Distribute to Firebase"
  lane :distribute do
    firebase_app_distribution(
      app: ENV["APPID"],
      groups: "testers",
      firebase_cli_path: "/usr/local/bin/firebase",
      ipa_path: "build/Runner.ipa"
    )
   end
end
