# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Increment Build Number"
  lane :increment_build do
    # Get the last version code and increment it.
    versionCode = File.read("metadata/versionCode").to_i
    versionCode = versionCode +1

    f = File.new("metadata/versionCode", "w")
    f.write(versionCode)
    f.close

    sh "git commit -a -m \"Updated Android version to #{version_string}\""
    add_git_tag(tag: "#{version_string}")
    push_to_git_remote
  end

  desc "Make Android Build"
  lane :build do
    # Build Android
    gradle(task: "clean assembleRelease")
  end

  desc "Distribute to Firebase"
  lane :distribute do
    firebase_app_distribution(
        app: ENV["APPID"],
        groups: "testers",
        firebase_cli_path: "/usr/local/bin/firebase",
        apk_path: "../build/app/outputs/apk/release/app-release.apk"
    )
  end
end
